AttendanceSystem/Controllers/AttendanceController.cs
using BusinessLogic;
using CustomModels.Collection;
using CustomModels.Identity;
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CustomModels.ReportModels;
using AttendanceSystem.Models;
using System.Net.Http;
using System.IO;

namespace AttendanceSystem.Controllers
{
    public class AttendanceController : Controller
    {
        //GET: Attendance
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetAttendances(DataTableAjaxPostModel searchModel)
        {
            var userParameters = new UserParameters();

            //user parameters
            TempData["userId"] = Singleton.Instance.UserId;
            var userProperties = new Helpers.Helpers().GetUserProperties(Singleton.Instance.UserId);
            userParameters.UserId = userProperties.UserId;
            userParameters.MachineId = userProperties.MachineId;
            userParameters.UserRole = userProperties.UserRole;
            userParameters.AjaxSearchParameters = searchModel;

            var result = new Logic().ViewAllAttendance(userParameters);

            return Json(new { data = result.Attendances, draw = Request.Form["draw"], recordsTotal = result.TotalRecordCount, recordsFiltered = result.FilteredRecordCount });

        }

        public string Create()
        {
            Stream req = Request.InputStream;
            req.Seek(0, System.IO.SeekOrigin.Begin);
            string json = new StreamReader(req).ReadToEnd();
            bool result = true;
            var jsonList = JObject.Parse(json);
            var attendance = JsonConvert.DeserializeObject<AttendanceFormat>(jsonList.ToString());
            if (string.IsNullOrEmpty(attendance.Error) && attendance.UserId.Count > 0)
            {
                result = new Logic().AddAttendance(attendance);
            }
            return (result == true ? "1" : "0");
        }

        public ActionResult CreateManually()
        {
            var userProperties = new SelectUserProperties { UserId = Singleton.Instance.UserId, CompanyId = Singleton.Instance.CompanyId, BranchId = Singleton.Instance.BranchId, DepartmentId = Singleton.Instance.DepartmentId };

            var users = new UserLogic().GetAllUsers(EnumLibrary.UserType.Administrator, userProperties);
            TempData["users"] = users;
            return View(new AttendanceViewModel());
        }

        [HttpPost]
        public ActionResult CreateManually(AttendanceViewModel model)
        {
            try
            {
                if (model.Image != null)
                {
                    var pic = Path.GetFileName(model.Image.FileName);
                    var mappedPath = Server.MapPath("/Images/AttendanceAttachments");
                    if (!Directory.Exists(mappedPath))
                        Directory.CreateDirectory(mappedPath);
                    var path = Path.Combine(mappedPath, pic);
                    model.Image.SaveAs(path);
                    model.ImageUrl = "/Images/AttendanceAttachments/" + pic;
                }

                var attendance = new Logic().GetUser(model.UserId);
                model.MacAddress = attendance.MacAddress;
                model.BranchId = attendance.BranchId;
                model.MachineId = attendance.MachineId;
                model.ManualEntry = true;
                var result = new Logic().AddManualAttendance(model);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return View();
            }
        }

        public ActionResult Edit(Guid id)
        {
            return View(new Logic().GetAttendance(id));
        }

        [HttpPost]
        public ActionResult Edit(AttendanceViewModel model)
        {
            var result = new Logic().EditAttendance(model);
            return RedirectToAction("Index", new { id = result });
        }

        public ActionResult Delete(int id)
        {
            return View();
        }

    }
}

AttendanceSystem/Controllers/LeaveController.cs
using AutoMapper;
using BusinessLogic;
using CustomModels.Collection;
using CustomModels.ReportModels;
using EnumLibrary;
using Helpers;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace AttendanceSystem.Controllers
{
    public class LeaveController : Controller
    {
        // GET: Leave
        public ActionResult Index()
        {
            var result = new Logic().GetLeaves<LeaveViewModel>(new LeaveViewModel());
            return View(result);
        }

        public ActionResult ViewLeave(string id)
        {
            TempData["id"] = id;
            var details = new Helpers.Helpers().GetUserProperties(id);
            ViewBag.departmentId = details.DepartmentId;
            
            var result = new Logic().GetLeaves<Leave>(new LeaveViewModel { UserId = id });
            if (result != new List<Leave>())
            {
                return View(result);
            }
            return View();
        }
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            var check = new LeaveViewModel();
            return View(check);
        }

        [HttpPost]
        public ActionResult Create(LeaveViewModel model)
        {
            // Function to process rules for current leave
            var processedResult = new Logic().ProcessRulesForLeaveCreation(model);
            if(processedResult == "true")
            {
                if (model.Image != null)
                {
                    var pic = Path.GetFileName(model.Image.FileName);
                    var mappedPath = Server.MapPath("/Images/LeaveAttachments");
                    if (!Directory.Exists(mappedPath))
                        Directory.CreateDirectory(mappedPath);
                    var path = Path.Combine(mappedPath, pic);
                    model.Image.SaveAs(path);
                    model.ImageUrl = "/Images/LeaveAttachments/" + pic;
                }
                var check = new Logic().CreateLeave(model);
                if (check != new Guid())
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    SetSelect2List(model);
                    return View(model);
                }
            }
            else
            {
                SetSelect2List(model);
                ModelState.AddModelError("StartingDate", processedResult);
                return View(model);
            }
        }
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(Guid id)
        {
            var result = new Logic().GetLeaves<LeaveViewModel>(new LeaveViewModel { Id = id }).FirstOrDefault();
            result.EditedLeaveDayCount = BusinessLogic.Rules.SortLeaves(result, new LeaveRulesDetailViewModel { IncludeHolidays = result.Type == LeaveType.Casual ? true : false });
            return View(result);
        }

        [HttpPost]
        public ActionResult Edit(LeaveViewModel model)
        {
            model.SkipLeave = model.Id;
            var processedResult = new Logic().ProcessRulesForLeaveCreation(model);
            if (processedResult == "true")
            {
                //model.EndingDate = model.EndingDate.AddSeconds(-1);
                var result = new Logic().EditLeave(model);
                if (result != new Guid())
                {
                    return RedirectToAction("Index");
                }
                return View(model);
            }

            else
            {
                SetSelect2List(model);
                ModelState.AddModelError("StartingDate", processedResult);
                return View(model);
            }

        }

        [Authorize(Roles = "Administrator")]
        public ActionResult SyncLeaves()
        {
            var model = InitializeDetailList(new LeaveDetailViewModel { LeaveTypeDetailList = new List<LeaveTypeDetailViewModel>() });
            return View(model);
        }

        [HttpPost]
        public ActionResult SyncLeaves(LeaveDetailViewModel model)
        {
            var result = new Logic().Update(model);
            if (result == new Guid())
                return View();
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult CreateRules()
        {
            return View(new LeaveRulesDetailViewModel());
        }

        [NonAction]
        public ActionResult CreateRuleDetail()
        {
            return View(new LeaveRulesDetailViewModel());
        }

        public ActionResult CreateRuleDetailPartial(LeaveRulesDetailViewModel model)
        {
            model.Action = model.Id == new Guid() ? "Create" : "Edit";
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult CreateRuleDetail(LeaveRulesDetailViewModel model)
        {
            var result = new Logic().Create(model);
            if (result != new Guid())
            {
                if (Request.IsAjaxRequest())
                    return Json(true, JsonRequestBehavior.AllowGet);

                return RedirectToAction("Index", "Home");
            }
            else
            {
                if (Request.IsAjaxRequest())
                    return Json(false, JsonRequestBehavior.AllowGet);

                return View(model);

            }
        }

        [HttpPost]
        public ActionResult EditRuleDetail(LeaveRulesDetailViewModel model)
        {
            var result = new Logic().Edit(model);
            if(result!=new Guid())
            {
                if (Request.IsAjaxRequest())
                    return Json(true, JsonRequestBehavior.AllowGet);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                if (Request.IsAjaxRequest())
                    return Json(false, JsonRequestBehavior.AllowGet);
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult DeleteRuleDetail(LeaveRulesDetailViewModel model)
        {
            model.IsDeleted = true;
            var result = new Logic().Edit(model);
            if (result != new Guid())
            {
                if (Request.IsAjaxRequest())
                    return Json(true, JsonRequestBehavior.AllowGet);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                if (Request.IsAjaxRequest())
                    return Json(false, JsonRequestBehavior.AllowGet);
                return View(model);
            }
        }

        public ActionResult Delete(Guid id)
        {
            var result = new Logic().GetLeaves<LeaveViewModel>(new LeaveViewModel { Id = id }).FirstOrDefault();
            return View(result);
        }

        [HttpPost]
        public ActionResult Delete(LeaveViewModel model)
        {
            var result = new Logic().DeleteLeave(model);
            if (result != new Guid())
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Details(Guid id)
        {
            
            var result = new Logic().GetLeaves<Leave>(new LeaveViewModel { Id = id }).FirstOrDefault();
            return View(result);
        }

        public ActionResult LeaveDetailCreatePartial()
        {
            var model = new RegisterViewModel { LeaveDetail = new LeaveDetailViewModel { LeaveTypeDetailList = new List<LeaveTypeDetailViewModel>() } };
            model.LeaveDetail = InitializeDetailList(model.LeaveDetail);
            return PartialView(model);
        }

        public ActionResult GetLeaveDetailForLeaveCreation(string employeeId)
        {
            var model = new LeaveDetailViewModel { LeaveTypeDetailList = new List<LeaveTypeDetailViewModel>() };
            var details = new Logic().GetLeaveDetail(new LeaveDetailSearchViewModel { EmployeeId = employeeId, SearchType = LeaveDetailSearchType.EmployeeId });
            if (details.Count() > 0)
            {
                model.EmployeeId = details.First().EmployeeId;
                foreach (var item in details)
                {
                    if(item.Type != LeaveType.Any)
                    model.LeaveTypeDetailList.Add(new LeaveTypeDetailViewModel { Type = item.Type, Count = item.Count, Description = item.Description });
                }
            }

            return PartialView(model);
        }

        public ActionResult AssignRules()
        {
            return View(new LeaveRuleViewModel());
        }

        public ActionResult AssignRulesPartial(LeaveRuleViewModel model)
        {
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult AssignRule(LeaveRuleViewModel model)
        {
            var result = new Logic().Create(model);
            if(result != new Guid())
            {
                if (Request.IsAjaxRequest())
                    return Json(true, JsonRequestBehavior.AllowGet);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                if (Request.IsAjaxRequest())
                    return Json(false, JsonRequestBehavior.AllowGet);
                return View(model);
            }
        }

        public JsonResult GetAssignedRuleEditPartial(Guid id)
        {
            return Json(new Logic().GetAllAssignedRules(new LeaveRuleViewModel { Id = id }).First(), JsonRequestBehavior.AllowGet);
        }

        //[HttpPost]
        public ActionResult EditAssignedRule(LeaveRuleViewModel model)
        {
            var result = new Logic().Edit(model);
            if(result != new Guid())
            {
                if (Request.IsAjaxRequest())

AttendanceSystem/Controllers/NationalHolidaysController.cs
using BusinessLogic;
using CustomModels.Collection;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AttendanceSystem.Controllers
{
    public class NationalHolidaysController : Controller
    {
        // GET: NationalHolidays

        public ActionResult Calendar()
        {
            return View();
        }

        [HttpPost]
        public JsonResult CreateJson()
        {
            NationalHoliday nationalHoliday = new NationalHoliday
            {
                Title = Request["title"],
                Description = Request["description"],
                StartDate = Convert.ToDateTime(Request["start"]),
                EndDate = Convert.ToDateTime(Request["end"])
            };

            var result = new Logic().CreateNationalHoliday(nationalHoliday);
            return result != new Guid() ? Json(new { result }) : Json(new { success = false });
        }

        public JsonResult GetJsonResult()
        {
            var result = new Logic().GetAllHolidays();
            return this.Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EditJson()
        {
            NationalHoliday model = new NationalHoliday();
            model.Title = Request["title"];
            model.Description = Request["description"];
            model.StartDate = Convert.ToDateTime(Request["start"]);
            model.EndDate = Convert.ToDateTime(Request["end"]);
            if (Request["permanent"] == "true") { model.Permanent = true; }
            else { model.Permanent = false; }
            model.Id = new Guid(Request["id"]);
            Logic lg = new Logic();
            var result = lg.EditNationalHoliday(model);
            if (result != new Guid())
            {
                return RedirectToAction("Calendar");
            }
            return View();
        }

        [HttpPost]
        public ActionResult DeleteJson()
        {
            NationalHoliday model = new NationalHoliday
            {
                Id = new Guid(Request["id"])
            };
            var result = new Logic().DeleteNationalHoliday(model);
            return result != new Guid() ? View("Calendar") : View();
        }

        public ActionResult Details(Guid id)
        {
            var result = new Logic().GetNationalHoliday(id);
            return View(result);
        }

        public ActionResult Practice()
        {
            return View();
        }
    }
}

AttendanceSystem/Views/Shared/_CalendarLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Scripts.Render("~/bundles/jqueryfullcalendar")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        @Html.Partial("_NavbarPartial")
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Centangle Interactive</p>
        </footer>
    </div>
</body>
</html>

AttendanceSystem/Views/Shared/_JqsLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Scripts.Render("~/bundles/jq")
    @Styles.Render("~/Content/jqCss")
    @Scripts.Render("~/bundles/modernizr")

   
</head>
<body>
    @Html.Partial("_SidebarPartial")
    <div class="navbar navbar-inverse navbar-fixed-top">
        @Html.Partial("_NavbarPartial")
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Centangle Interactive</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AttendanceSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
   
  
</head>
<body>
    @*@Html.Partial("_SidebarPartial")*@
    <div class="navbar navbar-inverse navbar-fixed-top">
        @Html.Partial("_NavbarPartial")
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Centangle Interactive</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>

AttendanceSystem/Views/Shared/_NavbarPartial.cshtml
@using AttendanceSystem.Models;

@{
    var logoUrl = "";
    if (User.Identity.IsAuthenticated)
    {
        logoUrl = Singleton.Instance.LogoUrl;
    }
    else
    {
        logoUrl = "Images/Company_Logo/Centangle.png";
    }
}
<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <button aria-controls="bs-navbar" id="menu-toggle" aria-expanded="false" class="collapsed navbar-toggle" data-target="#bs-navbar"
                data-toggle="collapse" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="toggle-icon"></span>
            <span class="toggle-icon"></span>
            <span class="toggle-icon"></span>
        </button>
        <a href="Index"> <img src="~/@logoUrl" width="60" alt="Company Logo" /></a>

        @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
    </div>
    <div class="navbar-collapse collapse bar">
      
        @Html.Partial("_LoginPartial")
    </div>
</div>

AttendanceSystem/Views/Shared/_ReportLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/modernizr")



    @*<script src="~/Scripts/fullcalendar.min.js"></script>*@
    @using CustomModels.Collection;
  
</head>
<body>
    
    <div class="navbar navbar-inverse navbar-fixed-top">
       
        @Html.Partial("_NavbarPartial")
    </div>
    <div id="wrapper">
        <button aria-controls="bs-navbar" id="menu-toggle" aria-expanded="false" class="collapsed navbar-toggle" data-target="#bs-navbar"
                data-toggle="collapse" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="toggle-icon"></span>
            <span class="toggle-icon"></span>
            <span class="toggle-icon"></span>
        </button>
        @Html.Partial("_SidebarPartial")
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">

                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Centangle Interactive</p>
        </footer>
    </div>

                    @Scripts.Render("~/bundles/bootstrap")
                    @RenderSection("scripts", required: false)
</body>
</html>

AttendanceSystem/Views/Shared/_SidebarPartial.cshtml
@*<link href="~/Content/themes/CustomCss/Sidebar.css" rel="stylesheet" />
    <link href="~/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css" rel="stylesheet" />
    <script src="~/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.js"></script>
    <script src="~/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js">

    </script>

    <div class="wrapper">

        <nav id="sidebar">
            <!-- Sidebar Header -->
            <div class="sidebar-header">
                <h3>Collapsible Sidebar</h3>
            </div>

            <!-- Sidebar Links -->
            <ul class="list-unstyled components">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li>
                    <!-- Link with dropdown items -->
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">Pages</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li><a href="#">Page</a></li>
                        <li><a href="#">Page</a></li>
                        <li><a href="#">Page</a></li>
                    </ul>
                <li><a href="#">Portfolio</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>

        <div id="content">
            <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                <i class="glyphicon glyphicon-align-left"></i>
                Toggle Sidebar
            </button>
        </div>

    </div>*@
<link href="~/Content/simple-sidebar.css" rel="stylesheet">

<!-- Sidebar -->
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
        @if (User.Identity.IsAuthenticated)
        {
            <li>@Html.ActionLink("Report", "Index", "Report")</li>
        }
        @if (User.IsInRole("Administrator") || User.IsInRole("Company Manager") || User.IsInRole("Branch Manager"))
        {

            <li>@Html.ActionLink("Leaves", "Index", "Leave")</li>
            <li>@Html.ActionLink("Add Manual Entry", "CreateManually", "Attendance")</li>
            <li>@Html.ActionLink("Company", "Index", "Company")</li>
            <li>@Html.ActionLink("Branch", "Index", "Branch")</li>
            <li>@Html.ActionLink("Department", "Index", "Department")</li>
            <li>@Html.ActionLink("Holidays", "Calendar", "NationalHolidays")</li>

        }

        @if (User.IsInRole("Administrator"))
        {
            <li>@Html.ActionLink("Schedule", "Index", "Schedule")</li>
            <li>@Html.ActionLink("Upload Users", "Index", "ExcelImport")</li>
        }
    </ul>
</div>
    <!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <!-- /#page-content-wrapper -->