AttendanceSystem/Controllers/DepartmentController.cs
using BusinessLogic;
using CustomModels;
using CustomModels.Collection;
using EnumLibrary;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AttendanceSystem.Controllers
{
    public class DepartmentController : Controller
    {
        // GET: Department
        [Authorize]
        public ActionResult Index(Guid? id, bool individual=false)
        {
            var result = new List<Department>();

            if (individual)
            {
                result = new Logic().ViewDepartments(id, 0);
            }
            else if (User.IsInRole("Administrator"))
            {
                result = new Logic().ViewDepartments(id, UserType.Administrator);
            }
            else if (User.IsInRole("Company Manager"))
            {
                result = new Logic().ViewDepartments(id, UserType.CompanyManager);
            }
            else if (User.IsInRole("Branch Manager"))
            {
                result = new Logic().ViewDepartments(id, UserType.BranchManager);
            }
            else if (User.IsInRole("Member")|| User.IsInRole("Department Manager"))
            {
                result = new Logic().ViewDepartments(id, UserType.Member);
            }
            
         
            return View(result);
        }

        public ActionResult Create()
        {
            var branchList = new Logic().GetBranches();
            TempData["branchList"] = branchList;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Department model)
        {
            if (ModelState.IsValid)
            {
                if(new Logic().CreateDepartment(model) != new Guid())
                {
                    return RedirectToAction("Index", new {});
                }
            }
            
            return View();
        }

        public ActionResult Edit(Guid id)
        {
            var branchList = new Logic().GetBranches();
            TempData["branchList"] = branchList;
            var data = new Logic().GetDepartment(id);
            if (data != null)
            {
                return View(data);
            }
            return View();
        }

        [HttpPost]
        public ActionResult Edit(Department model)
        {
            Guid result = new Logic().DepartmentEdit(model);
            if (result != new Guid())
                return RedirectToAction("Index");
            return View();
        }

        public ActionResult Delete(Guid id)
        {
            var result = new Logic().GetDepartment(id);
            if (result != null)
            {
                return View(result);
            }
            return View();
        }
        [HttpPost]
        public ActionResult Delete(Department model)
        {
            Logic lg = new Logic();
            var result = lg.DepartmentDelete(model);
            if (result != new Guid())
            {
                return RedirectToAction("Index");
            }
            else
                return View();
        }

        public ActionResult Details(Guid id)
        {
            Logic lg = new Logic();
            var result = lg.GetDepartment(id);
            if (result != null && result.Active == true)
            {
                return View(result);
            }
            else
                return View();
        }
        /// <summary>
        /// Gets list of Department on the base of branch Id
        /// </summary>
        /// <param name="id"></param>
        /// <returns>List of Departments as a JSON</returns>
       public JsonResult DepartmentList(string id)
        {
            var branchId = Guid.Parse(id);
            var result = new Logic().GetDepartmentList(branchId);
            return Json(result, JsonRequestBehavior.AllowGet);

        }
    }
}

AttendanceSystem/Views/Department/Create.cshtml
@model CustomModels.Collection.Department
@using CustomModels.Collection;
@{
    Layout = "~/Views/Shared/TablerLayout/_TablerLayout.cshtml";
    ViewBag.Title = "Create";
    var branchList = TempData["branchList"] != null ? (List<Branch>)TempData["branchList"] : new List<Branch>();
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Department", FormMethod.Post, htmlAttributes: new { @class = "card" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4 class="pt-5 pl-5">Department</h4>
    <hr />
    <div class="row col-md-12">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="col-md-6">
            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.BranchCode, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.BranchCode, new SelectList(branchList, "Id", "Name"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BranchCode, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
       


        <div class="form-group col-md-12">
            <div class="col-md-10">
                <input type="submit" value="Create" class="btn btn-default float-right" />
            </div>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AttendanceSystem/Views/Department/Delete.cshtml
@model CustomModels.Collection.Department

@{
    Layout = "~/Views/Shared/TablerLayout/_TablerLayout.cshtml";
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4 class="pt-5 pl-5">Department</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BranchCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Branch.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new { id = Model.BranchCode })
        </div>
    }
</div>

AttendanceSystem/Views/Department/Details.cshtml
@model CustomModels.Collection.Department

@{
    Layout = "~/Views/Shared/TablerLayout/_TablerLayout.cshtml";
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4 class="pt-5 pl-5">Department</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BranchCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Branch.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index", new { id=Model.BranchCode})
</p>

AttendanceSystem/Views/Department/Edit.cshtml
@model CustomModels.Collection.Department
@using CustomModels.Collection;
@{
    Layout = "~/Views/Shared/TablerLayout/_TablerLayout.cshtml";
    ViewBag.Title = "Edit";
    var branchList = TempData["branchList"] != null ? (List<Branch>)TempData["branchList"] : new List<Branch>();
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Department", FormMethod.Post, htmlAttributes: new { @class = "card" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 class="pt-5 pl-5">Department</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="col-md-12 row">
            <div class="col-md-6">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.BranchCode, "Branch Name", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.BranchCode, new SelectList(branchList, "Id", "Name", Model.BranchCode), htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.BranchCode, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group col-md-12 row">
                <div class="col-md-10">
                    <input type="submit" value="Save" class="btn btn-default float-right" />
                </div>
            </div>

        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AttendanceSystem/Views/Department/Index.cshtml
@model IEnumerable<CustomModels.Collection.Department>

@{
    Layout = "~/Views/Shared/TablerLayout/_TablerLayout.cshtml";
    ViewBag.Title = "Index";
    var companyId = Session["companyId"] != null ? Guid.Parse(Session["companyId"].ToString()) : new Guid();
    var branchId = TempData["branchId"] != null ? Guid.Parse(TempData["branchId"].ToString()) : new Guid();

}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { id = branchId })
</p>
<div class="row row-cards row-deck">
    <div class="col-12">
        <div class="card">
            <div class="table-responsive">
                <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                Branch Name
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.BranchName)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-secondary btn-sm" }) 
                                    @*@Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-secondary btn-sm" })*@ 
                                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-secondary btn-sm" }) 
                                    @Html.ActionLink("Employees", "../Account/Index1", new { id = item.Id }, new { @class = "btn btn-secondary btn-sm" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>