AttendanceSystem/Controllers/BranchController.cs
using CustomModels;
using CustomModels.Collection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLogic;
using Microsoft.AspNet.Identity;
using AttendanceSystem.Models;

namespace AttendanceSystem.Controllers
{
    public class BranchController : Controller
    {
        // GET: Branch
        [Authorize]
        public ActionResult Index()
        {
            Logic lg = new Logic();
            var result = lg.GetBranches(new BranchSearchViewModel ());
            if (result != null)
            {
                return View(result);
            }
            return View();
        }

        public ActionResult GetBranches(Guid id)
        {
            if(User.IsInRole("Administrator"))
            {
                var result = new Logic().GetBranches();
                if (result != null)
                {
                    return View(result);
                }
            }
            else
            {
                var userId = User.Identity.GetUserId();
                var details = new Helpers.Helpers().GetUserProperties(userId);
                var result = new Logic().GetBranches(new BranchSearchViewModel{CompanyId = details.CompanyId});
                if (result != null)
                {
                    return View(result);
                }
            }
            return View();
        }

        public ActionResult Create()
        {
            var companyList = new Logic().GetCompanies(new CompanySearchViewModel { GetAllCompanies = true});
            return View();
        }
        [HttpPost]
        public ActionResult Create(Branch model)
        {
            if (ModelState.IsValid)
            {
                model.CompanyId = Singleton.Instance.CompanyId;
                var result = new Logic().AddBranch(model);
                if (result != new Guid())
                    return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Edit(Guid id)
        {
            var result = new Logic().GetBranches(new BranchSearchViewModel { Id = id}).FirstOrDefault();
            if (result != null)
            { 
                TempData["addressId"] = result.AddressId;
            return View(result);
            }
            return View();
        }
        [HttpPost]
        public ActionResult Edit(Branch model)
        {
            Logic lg = new Logic();
            model.AddressId = Guid.Parse(TempData["addressId"].ToString());
            var result = lg.EditBranch(model);
            if (result != new Guid())
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Delete(Guid id)
        {
            return View(new Logic().GetBranches(new BranchSearchViewModel { Id = id }).FirstOrDefault());
        }

        [HttpPost]
        public ActionResult Delete(Branch model)
        {
            var result = new Logic().DeleteBranch(model);
            if (result != new Guid())
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Details(Guid id)
        {
            return View(new Logic().GetBranches(new BranchSearchViewModel { Id = id }).FirstOrDefault());
        }
    }
}

AttendanceSystem/Controllers/CompanyController.cs
using AutoMapper;
using BusinessLogic;
using CustomModels.Collection;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AttendanceSystem.Controllers.CompanyController
{
    public class CompanyController : Controller
    {
        // GET: Company
        [Authorize]
        public ActionResult Index()
        {
            var result = new Logic().GetCompanies(new CompanySearchViewModel { GetAllCompanies=true});

            if (result != new List<Company>())
            {
                return View(result);
            }
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public ActionResult Create(CompanyViewModel model, HttpPostedFileBase logo)
        {
            if (logo != null)
            {
                var pic = System.IO.Path.GetFileName(model.Logo.FileName);
                var path = System.IO.Path.Combine(
                                   Server.MapPath("~/Images/Company_Logo"), pic);

                model.Logo.SaveAs(path);
                model.LogoUrl = "/Images/Company_Logo/" + pic;
            }

            var result = new Logic().CreateCompany(model);
            if (result != new Guid())
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(Guid id)
        {
            var result = new Logic().GetCompanies(new CompanySearchViewModel { Id = id }).FirstOrDefault();
            var config = new MapperConfiguration(cfg => { cfg.CreateMap<Company, CompanyViewModel>(); });
            var iMapper = config.CreateMapper();
            var model = result != null ? iMapper.Map<Company, CompanyViewModel>(result) : new CompanyViewModel();
            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public ActionResult Edit(CompanyViewModel model, HttpPostedFileBase logo)
        {
            if (logo != null)
            {
                var pic = System.IO.Path.GetFileName(model.Logo.FileName);
                var path = System.IO.Path.Combine(
                                   Server.MapPath("~/Images/Company_Logo"), pic);

                model.Logo.SaveAs(path);
                model.LogoUrl = "/Images/Company_Logo/" + pic;
            }
            var result = new Logic().EditCompany(model);
            if (result != new Guid())
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(Guid id)
        {
            return View(new Logic().GetCompanies(new CompanySearchViewModel { Id = id }).FirstOrDefault());
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public ActionResult Delete(Company model)
        {
            Logic lg = new Logic();
            var result = lg.DeleteCompany(model);
            if (result != new Guid())
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Details(Guid id)
        {
            return View(new Logic().GetCompanies(new CompanySearchViewModel { Id = id }).FirstOrDefault());
        }

        public ActionResult PolicyIndex(Guid id)
        {
            TempData["companyId"] = id;
            var result = new Logic().GetCompanyPolicies(new CompanyPolicySearchViewModel { CompanyId = id });
            return View(result);
        }

        [Authorize(Roles = "Administrator, Company Manager")]
        public ActionResult AddPolicy(Guid id)
        {
            Session["id"] = id;
            return View();
        }

        [Authorize(Roles = "Administrator, Company Manager")]
        [HttpPost]
        public ActionResult AddPolicy(CompanyPolicy model)
        {
            model.CompanyId = Guid.Parse(Session["id"].ToString());
            model.Active = true;
            var result = new Logic().AddPolicy(model);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administrator, Company Manager")]
        public ActionResult EditPolicy(Guid id)
        {
            return View(new Logic().GetCompanyPolicies(new CompanyPolicySearchViewModel { Id = id }).First());
        }

        [Authorize(Roles = "Administrator, Company Manager")]
        [HttpPost]
        public ActionResult EditPolicy(CompanyPolicy model)
        {
            model.CompanyId = Guid.Parse(Session["id"].ToString());
            var result = new Logic().EditPolicy(model);
            return RedirectToAction("PolicyIndex", new { id = model.CompanyId });
        }

        [Authorize(Roles = "Administrator, Company Manager")]
        public ActionResult DeletePolicy(Guid id)
        {
            return View(new Logic().GetCompanyPolicies(new CompanyPolicySearchViewModel { Id = id }));
        }

        [Authorize(Roles = "Administrator, Company Manager")]
        [HttpPost]
        public ActionResult DeletePolicy(CompanyPolicy model)
        {
            new Logic().DeletePolicy(model);
            return RedirectToAction("Index");
        }

    }
}

AttendanceSystem/Views/Branch/Create.cshtml
@model CustomModels.Collection.Branch
@using CustomModels.Collection;

@{
    Layout = "~/Views/Shared/TablerLayout/_TablerLayout.cshtml";
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Branch", FormMethod.Post, htmlAttributes:new { @class="card"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4 class="mt-5 ml-5">Branch</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row col-md-12">

        <div class="col-md-6">
            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.Address.Area, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Address.Area, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.Area, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.Address.House, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Address.House, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.House, "", new { @class = "text-danger" })
                </div>
            </div>


        </div>

        <div class="col-md-6">

            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.Address.City, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Address.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.City, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.Address.Street, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Address.Street, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.Street, "", new { @class = "text-danger" })
                </div>
            </div>


        </div>
        <div class="form-group col-md-12 row">
            <div class="col-md-10">
                <input type="submit" value="Create" class="btn btn-default float-right" />
            </div>
        </div>
    </div>
  
</div>
}

<div>
    @Html.ActionLink("Back to Branches", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AttendanceSystem/Views/Branch/Delete.cshtml
@model CustomModels.Collection.Branch

@{
    Layout = "~/Views/Shared/TablerLayout/_TablerLayout.cshtml";

    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Branch</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
            @Html.HiddenFor(model=>model.Address)
            @Html.HiddenFor(model=>model.AddressId)
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AttendanceSystem/Views/Branch/Details.cshtml
@model CustomModels.Collection.Branch

@{
    Layout = "~/Views/Shared/TablerLayout/_TablerLayout.cshtml";

    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Branch</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.House)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.House)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.City)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AttendanceSystem/Views/Branch/Edit.cshtml
@model CustomModels.Collection.Branch

@{
    Layout = "~/Views/Shared/TablerLayout/_TablerLayout.cshtml";

    ViewBag.Title = "Edit";

}

<h2>Edit</h2>


@using (Html.BeginForm("Edit","Branch",FormMethod.Post,htmlAttributes:new { @class = "card" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4 class="mt-5 ml-5">Branch</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="row col-md-12">
        <div class="col-md-6">
            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

           
            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.Address.Street, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Address.Street, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.Street, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.Address.Area, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Address.Area, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.Area, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-6">

            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.Address.House, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Address.House, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.House, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.Address.City, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Address.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.City, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group col-md-12">
            <div class="col-md-10">
                <input type="submit" value="Save" class="btn btn-default float-right" />
            </div>
        </div>

    </div>
   
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AttendanceSystem/Views/Branch/GetBranches.cshtml
@model IEnumerable<CustomModels.Collection.Branch>

@{
    ViewBag.Title = "GetBranches";
   

}

<h2>Branches</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-striped table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Company.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address.Area)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Company.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address.Area)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @*@Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
            @Html.ActionLink("Delete", "Delete", new { id = item.Id }) @*|
            @Html.ActionLink("Departments","../Department/Index")*@
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("Back to Company", "Index","Company",  new { }, "")
</p>

AttendanceSystem/Views/Branch/Index.cshtml
@model IEnumerable<CustomModels.Collection.Branch>

@{
    Layout = "~/Views/Shared/TablerLayout/_TablerLayout.cshtml";

    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="row row-cards row-deck">
    <div class="col-12">
        <div class="card">
            <div class="table-responsive">
                <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Address.House)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Address.Street)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Address.Area)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Address.City)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Address.House)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Address.Street)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Address.Area)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Address.City)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-secondary btn-sm" }) 
                                    @*@Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-secondary btn-sm" })*@ 
                                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-secondary btn-sm" }) 
                                    @Html.ActionLink("Departments", "../Department/Index", new { id = item.Id, individual = true }, new { @class = "btn btn-secondary btn-sm" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>